name: MySQL Backup and Discord Upload

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch: # 수동 실행도 가능

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 ssh 접속
        uses: appleboy/ssh-action@master # ssh 접속 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          debug: true # 디버그 모드 활성화
          script:
            echo " - MySQL dump - "
            sudo docker exec ${{ secrets.MYSQL_CONTAINER}} mysqldump --set-gtid-purged=OFF -u ${{ secrets.MYSQL_USER}} -p${{ secrets.MYSQL_PASSWORD}} --databases ${{ secrets.MYSQL_DATABASES}} > dump.sql
            echo " - MySQL dump completed - "

      - name: SCP dump.sql from EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }} # EC2 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # EC2 사용자 이름
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # EC2 PEM 파일
          port: ${{ secrets.REMOTE_SSH_PORT }} # EC2 SSH 포트
          source: "dump.sql" # EC2에서 가져올 파일
          target: "./dump.sql" # 로컬 경로

      - name: Upload backup to Discord
        uses: peter-evans/discord-webhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Here is the latest MySQL backup file!'
          file: dump.sql
